version: '3.8'

# Docker-Compose 单容器使用参考 YAML 配置文件
# 更多配置参数请参考镜像 README.md 文档中说明
services:
  rabbitmq:
    image: 'colovu/rabbitmq'
    ports:
      - '5672:5672'
      - '61613:61613'
      - '15672:15672'
    environment:
      - RABBITMQ_USERNAME=admin
      - RABBITMQ_PASSWORD=colovu
      - RABBITMQ_ENABLE_PLUGINS=rabbitmq_stomp
      - RABBITMQ_STOMP_USERNAME=admin
      - RABBITMQ_STOMP_PASSWORD=colovu
